-- CreateEnum
CREATE TYPE "ReportCategory" AS ENUM ('SPAM', 'ILLEGAL_CONTENT', 'HARASSMENT', 'HATE_SPEECH', 'SEXUAL_CONTENT', 'VIOLENCE', 'MINOR_ENDANGERMENT', 'SPOILER', 'IMPERSONATION', 'MISINFORMATION', 'STOLEN_CONTENT', 'MISLEADING_REVIEW', 'OTHER');

-- CreateEnum
CREATE TYPE "ReportMotif" AS ENUM ('SPAM_PROMOTIONAL', 'SPAM_SUSPICIOUS_LINK', 'SPAM_REPEATED', 'ILLEGAL_PIRACY_LINK', 'HARASSMENT_INSULTS', 'HARASSMENT_THREATS', 'HARASSMENT_STALKING', 'HARASSMENT_DOXXING', 'HATE_RACISM', 'HATE_SEXISM_LGBTQ', 'HATE_OTHER', 'SEXUAL_EXPLICIT', 'VIOLENCE_GRAPHIC', 'MINOR_ENDANGERMENT_CONTENT', 'MINOR_ENDANGERMENT_SOLICITATION', 'SPOILER_UNTAGGED', 'IMPERSONATION_REAL_PERSON', 'IMPERSONATION_FAKE_ACCOUNT', 'MISINFORMATION_FALSE_FACT', 'STOLEN_CONTENT_PLAGIARIZED', 'MISLEADING_REVIEW_MANIPULATION');

-- AlterTable
ALTER TABLE "Report" ADD COLUMN     "category" "ReportCategory",
ADD COLUMN     "motif" "ReportMotif";

-- CreateIndex
CREATE INDEX "Report_category_idx" ON "Report"("category");
