import type { Domain, Role, SecurityEventType } from "../enums";

/** Which app area a dependency powers, for grouping in the admin services page. */
export type ServiceArea =
  | "Vidéo"
  | "Jeux"
  | "Livres"
  | "Musique"
  | "Podcasts"
  | "Jeux de société"
  | "Système";

/** Billing window a documented provider quota resets on. */
export type QuotaWindow = "day" | "month";

/** Health of one external dependency, as surfaced by the admin services page. */
export interface ServiceStatusDto {
  /** Stable identifier, e.g. "tmdb". */
  key: string;
  /** Human label, e.g. "TMDB". */
  label: string;
  area: ServiceArea;
  /**
   * Whether the app hard-fails for its area without this service. `false` for
   * optional enrichers (OMDb ratings) and keyless fallbacks (AniList).
   */
  required: boolean;
  /** Its API key/credentials are present in the environment. */
  configured: boolean;
  /**
   * Live probe result: `true`/`false` when probed, `null` when not probed
   * (unconfigured, or nothing cheap to ping).
   */
  reachable: boolean | null;
  /** Short human note (missing key, HTTP status, error reason…). */
  detail?: string;
  /** Round-trip time of the live probe, in ms. Absent when not probed. */
  latencyMs?: number;
  /** Where to obtain the missing key/credentials, shown when `!configured`. */
  keyUrl?: string;
  /** Calls recorded today (UTC). Absent for services with no call-based quota (e.g. webPush). */
  today?: number;
  /** Calls recorded this calendar month (UTC). Absent alongside `today`. */
  thisMonth?: number;
  /** Documented free-tier quota, when publicly known; absent otherwise. */
  limit?: { max: number; window: QuotaWindow };
  /** `today` or `thisMonth` (matching `limit.window`) relative to `limit.max`, as a percentage. Present only when `limit` is set. */
  percentUsed?: number;
  /**
   * Planned-but-unbuilt provider (podcasts, board games): shown with a "Bientôt"
   * badge and never probed. When set, `configured`/`reachable` are meaningless.
   */
  comingSoon?: boolean;
}

export interface ServiceStatusResponseDto {
  services: ServiceStatusDto[];
  /** When the probes ran (ISO 8601). */
  checkedAt: string;
}

/** One editable sample-data field for a gallery template (e.g. a recipient's display name). */
interface MailTemplateFieldDto {
  key: string;
  label: string;
  default: string;
  /** Renders as a `<textarea>` in the admin gallery instead of a single-line input. */
  multiline?: boolean;
}

/** One entry in the admin email-template gallery. */
export interface MailTemplateInfoDto {
  key: string;
  label: string;
  fields: MailTemplateFieldDto[];
}

export interface MailTemplateListResponseDto {
  templates: MailTemplateInfoDto[];
  /** Whether SMTP is configured — test-send is disabled otherwise. */
  smtpConfigured: boolean;
}

/** Rendered preview of one template (with sample data, possibly overridden), never sent. */
export interface MailTemplatePreviewDto {
  subject: string;
  html: string;
  text: string;
}

export interface SendTestEmailRequestDto {
  to: string;
  /** Overrides for the template's editable sample fields, by field key. */
  values?: Record<string, string>;
}

/** Which registered account to target when sending an admin test push. */
export interface SendAdminTestPushRequestDto {
  email: string;
  /** Defaults to a canned admin-test message when omitted. */
  title?: string;
  body?: string;
}

/** Outcome of the push send to one of the account's subscribed devices. */
interface AdminPushSendOutcomeDto {
  userAgent: string | null;
  ok: boolean;
  /** Present when `ok` is false (rejected/expired subscription, send error…). */
  error?: string;
}

export interface AdminPushSendResponseDto {
  /** How many devices the account had subscribed at send time. */
  subscriptionCount: number;
  results: AdminPushSendOutcomeDto[];
}

/** A push sent to every subscribed device on the instance, not just one account. */
export interface SendAdminBroadcastPushRequestDto {
  /** Defaults to a canned admin-broadcast message when omitted. */
  title?: string;
  body?: string;
}

export interface AdminPushBroadcastResponseDto {
  /** Distinct accounts targeted (at least one active subscription). */
  accountCount: number;
  /** Total devices targeted, across all those accounts. */
  deviceCount: number;
  successCount: number;
  failureCount: number;
}

/** One device an account has subscribed to push on. */
export interface AdminPushDeviceDto {
  id: string;
  userAgent: string | null;
  createdAt: string;
}

/**
 * Locally-generated architecture diagrams (Mermaid source), for the admin
 * schema page. Both are gitignored dev artifacts — `null` when not generated
 * yet (or not shipped in this deployment).
 */
export interface SchemaGraphResponseDto {
  /** Prisma ERD, from `docs/erd.md` (regenerated by `prisma generate`). */
  erd: string | null;
  /** NestJS module graph, from `docs/modules.md` (regenerated by `pnpm --filter @loomkeep/api run graph`). */
  modules: string | null;
}

export type JobStatus = "SUCCESS" | "FAILURE";

/** One completed execution of a scheduled/admin-triggered job. */
export interface JobRunDto {
  id: string;
  jobKey: string;
  startedAt: string;
  finishedAt: string;
  status: JobStatus;
  /** Short human outcome, e.g. "3 notification(s) créée(s)". */
  summary: string | null;
  /** Present only when `status` is "FAILURE". */
  error: string | null;
}

/** One background job the admin can inspect/trigger, with its recent runs. */
export interface JobDto {
  key: string;
  label: string;
  /** Cron schedule, human-readable (e.g. "Toutes les heures"). */
  schedule: string;
  /** Most recent runs first. */
  runs: JobRunDto[];
}

export interface JobListResponseDto {
  jobs: JobDto[];
}

/** Bucket granularity for the admin trend charts. */
export type TrendPeriod = "day" | "week" | "month" | "year";

/** One bucket in a trend series. */
export interface TrendPointDto {
  /** ISO date (UTC) of the bucket's start. */
  periodStart: string;
  count: number;
}

/**
 * The few instance counters the admin *dashboard* (/admin) and
 * /admin/communications need for their status strips — deliberately not a
 * statistics payload. Everything analytical lives on /admin/stats, section by
 * section (dto/admin-stats.ts); this is what remains of the former
 * `AdminStatsDto` once that page took over.
 */
export interface AdminOverviewDto {
  accounts: number;
  /** Accounts created since the start of the current weekly bucket. */
  newAccountsThisWeek: number;
  /** Accounts with at least one push subscription. */
  accountsWithPush: number;
  /** Push subscription rows (an account can have several devices). */
  pushDevices: number;
  /** Cached works across all four domains. */
  cachedItems: number;
}

/** One cached catalogue item (media/game/book/album), as browsed on the admin cache page. */
export interface AdminCacheItemDto {
  id: string;
  domain: Domain;
  title: string;
  coverUrl: string | null;
  canonicalSource: string;
  lastSyncedAt: string;
  createdAt: string;
  /** Distinct library/game/book/music entries pointing at this item, across every account. */
  referenceCount: number;
  /** Past the 24h refresh TTL. */
  stale: boolean;
}

/** How the cache list is ordered. `stale` (default) surfaces the least-fresh first. */
export type AdminCacheSort = "stale" | "recent" | "title";

export interface AdminCacheListResponseDto {
  items: AdminCacheItemDto[];
  /** Total items matching the current filters, across all pages. */
  total: number;
  /** How many items in this domain are past the 24h TTL — drives the "resync stale" action. */
  staleTotal: number;
  /** How many items in this domain have zero references — drives the "delete orphans" action. */
  orphanTotal: number;
}

/** One external identifier a cached item carries (its source + id in that source). */
interface AdminCacheExternalIdDto {
  source: string;
  externalId: string;
}

/**
 * Full detail of one cached item, shown in the admin cache drawer. Deliberately
 * light on catalogue metadata (overview, genres…) — that lives on the item's own
 * Loomkeep page, linked via `detailPath`; the drawer focuses on cache state.
 */
export interface AdminCacheItemDetailDto extends AdminCacheItemDto {
  /** When the DB row itself last changed (distinct from `lastSyncedAt`). */
  updatedAt: string;
  externalIds: AdminCacheExternalIdDto[];
  /** MEDIA only: seasons with their episode counts. Empty for other domains. */
  seasons: { number: number; title: string | null; episodeCount: number }[];
  /** In-app path to this item's public Loomkeep page (e.g. `/media/series/1396`). */
  detailPath: string;
}

/** Outcome of re-syncing every stale item in a domain. */
export interface AdminCacheResyncStaleResultDto {
  /** Items that refreshed successfully. */
  resynced: number;
  /** Items whose source refresh failed (left untouched). */
  failed: number;
}

/** Outcome of purging every orphaned (unreferenced) item in a domain. */
export interface AdminCacheDeleteOrphansResultDto {
  /** Items removed from the cache. */
  deleted: number;
  /** Orphans left alone because a review/comment/activity row still targets them. */
  skipped: number;
}

/** One registered account, as listed in the admin users page. */
export interface AdminUserDto {
  id: string;
  email: string;
  username: string;
  displayName: string;
  avatarUrl: string | null;
  emailVerified: boolean;
  role: Role;
  createdAt: string;
  /** Most recent `RefreshToken.lastUsedAt` across every device, null if never signed in. */
  lastActiveAt: string | null;
}

/** Extra server-side filter for the admin users list, on top of free-text search. */
export type AdminUserFilter = "all" | "admin" | "unverified" | "never";

export interface AdminUserListResponseDto {
  users: AdminUserDto[];
  page: number;
}

/** Compact breakdown of the works saved in one account's libraries. */
export interface AdminUserLibraryStatsDto {
  movies: number;
  series: number;
  anime: number;
  games: number;
  books: number;
  music: number;
  total: number;
}

/**
 * Minimal, unpaginated account list for a picker (UserSelector, the
 * communications broadcast target field) — distinct from `AdminUserDto`,
 * which now comes paginated from the admin users page itself.
 */
export interface AdminUserOptionDto {
  id: string;
  displayName: string;
  email: string;
}

export interface UpdateAdminUserRoleRequestDto {
  role: Role;
}

export interface AdminUserRoleDto {
  role: Role;
}

/**
 * One persisted backup dump on disk, for the admin "Sauvegarde" page's
 * list/download/delete UI. Produced by the daily `backup.run` cron (also
 * triggerable on demand from /admin/jobs or the Sauvegarde page itself) —
 * pruned to the 7 most recent.
 */
export interface AdminBackupFileDto {
  id: string;
  filename: string;
  sizeBytes: number;
  createdAt: string;
}

/** Full plain-SQL content of one persisted backup, for download. */
export interface AdminBackupFileContentDto {
  filename: string;
  sql: string;
}

/** Replaces the entire instance database with a previously downloaded dump. */
export interface AdminBackupRestoreRequestDto {
  sql: string;
}

/** Running app version, for the admin/settings footer. */
export interface AdminVersionDto {
  version: string;
}

/** One sensitive account action, as listed on the admin "Sécurité" page. */
export interface SecurityEventDto {
  id: string;
  type: SecurityEventType;
  /** Null once the account has since been deleted (USER_DELETED itself, or any earlier event on it). */
  userId: string | null;
  /** Email or username involved — kept even after the account is gone, so the trail stays legible. */
  identifier: string;
  /** Free-form context, e.g. the old → new email on an EMAIL_CHANGED event. */
  detail: string | null;
  userAgent: string | null;
  createdAt: string;
}

export interface SecurityEventListResponseDto {
  events: SecurityEventDto[];
  page: number;
}

/** One committed import (analyze-only runs write nothing and aren't logged here). */
export interface AdminImportRunDto {
  id: string;
  /** Null once the account has since been deleted — identifier below is kept. */
  userId: string | null;
  identifier: string;
  /** Import source id ("tvtime", "storygraph", "goodreads", "steam"). */
  sourceId: string;
  status: JobStatus;
  /** Items actually written, regardless of outcome. */
  itemCount: number;
  /** Whether the commit wiped the domain's library first (destructive replace). */
  overwrite: boolean;
  /** Human summary joined from the report's tiles; null on failure. */
  summary: string | null;
  /** Present only when `status` is "FAILURE". */
  error: string | null;
  startedAt: string;
  finishedAt: string;
}

export interface AdminImportRunListResponseDto {
  runs: AdminImportRunDto[];
  page: number;
}

/** Committed imports for one source, all accounts and all time. */
export interface AdminImportSourceStatDto {
  /** Import source id ("tvtime", "storygraph", "goodreads", "steam"). */
  sourceId: string;
  runs: number;
  /** Items written by those runs. */
  items: number;
}

/**
 * Header summary of the admin "Imports" page. Computed over every logged run,
 * never over the page currently displayed — the list is paginated and filtered,
 * so a client-side total would drift as soon as the admin scrolls or filters.
 */
export interface AdminImportSummaryDto {
  total: number;
  success: number;
  failure: number;
  /** Share (0-100) of runs that succeeded; null while nothing was ever imported. */
  successPercent: number | null;
  /** Most items first. */
  bySource: AdminImportSourceStatDto[];
}

/** One account ranked by how many reports it filed. */
export interface AdminTopReporterDto {
  username: string;
  reports: number;
}

/**
 * Header summary of the admin "Signalements" page, over the whole queue rather
 * than the cursor page on screen. Same figures as the /admin/stats "Social"
 * moderation card (they share the API-side helpers), plus the reporter ranking
 * that only makes sense next to the queue itself.
 */
export interface AdminReportsSummaryDto {
  pending: number;
  resolved: number;
  dismissed: number;
  /** Median hours between filing and closing; null while nothing is closed. */
  medianResolutionHours: number | null;
  /** Share (0-100) of closed reports acted on rather than dismissed; null while nothing is closed. */
  foundedPercent: number | null;
  topReporters: AdminTopReporterDto[];
}

/** One identifier targeted by failed logins over the summary's recent window. */
export interface AdminFailedLoginTargetDto {
  /** Email or username the failed attempts were made against. */
  identifier: string;
  failures: number;
}

/**
 * Header summary of the admin "Sécurité" page. Scoped to LOGIN_FAILED: the other
 * event types are deliberate account actions the log already reads well as a
 * list, whereas failed logins only mean something as a rate. The three windows
 * mirror the ones /admin/stats uses for account activity (24 h / 7 j / 30 j).
 */
export interface AdminSecuritySummaryDto {
  loginFailed24h: number;
  loginFailed7d: number;
  loginFailed30d: number;
  /** Every failed login ever logged. */
  loginFailedTotal: number;
  /** Most-targeted identifiers over the last 7 days, most failures first. */
  topTargets7d: AdminFailedLoginTargetDto[];
}

/** Active push subscriptions sharing one user-agent family. */
export interface AdminPushUserAgentStatDto {
  /** Browser family derived from the stored user-agent ("Chrome", "Safari", "Inconnu"…). */
  label: string;
  count: number;
}

/**
 * Header summary of the "Push" tab of admin "Communications". Active
 * subscriptions only, and deliberately no alive/dead ratio: a subscription the
 * push service rejects is deleted on the spot (see `PushService`), so a dead one
 * leaves no row to count.
 */
export interface AdminPushSummaryDto {
  /** Subscription rows on the instance (an account can have several devices). */
  subscriptions: number;
  /** Distinct accounts with at least one subscription. */
  accounts: number;
  /** Most devices first. */
  byUserAgent: AdminPushUserAgentStatDto[];
}
