-- AlterEnum
ALTER TYPE "ReportCategory" ADD VALUE 'NONCOMPLIANT_ACCOUNT' BEFORE 'OTHER';

-- AlterEnum
ALTER TYPE "ModerationMeasure" ADD VALUE 'LIST_REMOVED' BEFORE 'ACCOUNT_DELETED';
ALTER TYPE "ModerationMeasure" ADD VALUE 'LIST_EDITED' BEFORE 'ACCOUNT_DELETED';
ALTER TYPE "ModerationMeasure" ADD VALUE 'AVATAR_REMOVED' BEFORE 'ACCOUNT_DELETED';
ALTER TYPE "ModerationMeasure" ADD VALUE 'BIO_CLEARED' BEFORE 'ACCOUNT_DELETED';
ALTER TYPE "ModerationMeasure" ADD VALUE 'DISPLAY_NAME_CHANGED' BEFORE 'ACCOUNT_DELETED';
ALTER TYPE "ModerationMeasure" ADD VALUE 'ACCOUNT_SUSPENDED' BEFORE 'ACCOUNT_DELETED';

-- AlterEnum: IMPERSONATION_FAKE_ACCOUNT is dropped (bots moved to
-- NONCOMPLIANT_ACCOUNT). Any row still carrying it keeps its category and
-- falls back to the category's remaining motif.
CREATE TYPE "ReportMotif_new" AS ENUM ('SPAM_PROMOTIONAL', 'SPAM_SUSPICIOUS_LINK', 'SPAM_REPEATED', 'ILLEGAL_PIRACY_LINK', 'ILLEGAL_TERRORISM', 'ILLEGAL_DEFAMATION', 'ILLEGAL_OTHER', 'HARASSMENT_INSULTS', 'HARASSMENT_THREATS', 'HARASSMENT_STALKING', 'HARASSMENT_DOXXING', 'HATE_RACISM', 'HATE_SEXISM_LGBTQ', 'HATE_OTHER', 'SEXUAL_EXPLICIT', 'VIOLENCE_GRAPHIC', 'MINOR_ENDANGERMENT_CONTENT', 'MINOR_ENDANGERMENT_SOLICITATION', 'SPOILER_UNTAGGED', 'IMPERSONATION_REAL_PERSON', 'MISINFORMATION_FALSE_FACT', 'STOLEN_CONTENT_PLAGIARIZED', 'STOLEN_CONTENT_IMAGE', 'MISLEADING_REVIEW_MANIPULATION', 'MISLEADING_REVIEW_OFF_TOPIC', 'ACCOUNT_BOT', 'ACCOUNT_UNDERAGE', 'ACCOUNT_BAN_EVASION', 'ACCOUNT_MANIPULATION');
ALTER TABLE "Report" ALTER COLUMN "motif" TYPE "ReportMotif_new" USING (
  CASE WHEN "motif"::text = 'IMPERSONATION_FAKE_ACCOUNT' THEN 'IMPERSONATION_REAL_PERSON' ELSE "motif"::text END
)::"ReportMotif_new";
ALTER TABLE "ModerationDecision" ALTER COLUMN "reasonMotif" TYPE "ReportMotif_new" USING (
  CASE WHEN "reasonMotif"::text = 'IMPERSONATION_FAKE_ACCOUNT' THEN 'IMPERSONATION_REAL_PERSON' ELSE "reasonMotif"::text END
)::"ReportMotif_new";
ALTER TYPE "ReportMotif" RENAME TO "ReportMotif_old";
ALTER TYPE "ReportMotif_new" RENAME TO "ReportMotif";
DROP TYPE "ReportMotif_old";

-- CreateEnum
CREATE TYPE "ReportProfilePart" AS ENUM ('NAME', 'PHOTO', 'BIO', 'BEHAVIOUR');

-- AlterTable
ALTER TABLE "Report" ADD COLUMN "profilePart" "ReportProfilePart";

-- AlterTable
ALTER TABLE "User" ADD COLUMN "suspendedUntil" TIMESTAMP(3);
